routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware'=>'auth'], function(){
	Route::get('/orders/user', 'OrdersController@userIndex')->name('orders.user');
	Route::get('/orders/store', 'OrdersController@store')->name('orders.store');
	Route::get('/userprofile', 'UserController@index')->name('profile');
	Route::put('/userprofile', 'UserController@update')->name('updateprofile');
});

Route::group(['middleware'=>['auth', 'admin']], function(){
	Route::resource('/admin/dishes', 'AdminDishController', ['as'=>'admin']);
	Route::resource('/orders', 'OrdersController', ['except'=>['store']]);
	Route::resource('/reservation', 'TableReservationController');
	Route::resource('/adminusers', 'AdminUserController');
});

Route::get('/reservation/create', 'TableReservationController@create')->name('reservation.create');
Route::post('/reservation', 'TableReservationController@store')->name('reservation.store');

Route::get('/home', 'HomeController@index');
Route::get('/dishes', 'DishController@index')->name('dishes_list');
Route::get('/contacts', function (){
	return view('user.contact');
})->name('contacts');
Route::resource('cart', 'CartController');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Cart;

class Order extends Model
{
	protected $fillable = [
	'user_id', 'total'];

    public function user (){
    	return $this->belongsTo('App\User');
    }

    public function dishes(){
    	return $this->belongsToMany('App\Dish')->withPivot('price', 'quantity');
    }

    public function getTotalWithTax(){
        $dishes = $this->dishes;
        $total = 0;
        
        foreach($dishes as $dish){
            $total +=  $dish->pivot->quantity * $dish->pivot->price * 1.21;
        }
        
        $total = number_format($total, 2);
        return $total;
    }

    public function getTotalWithTaxAttribute(){
        return $this->getTotalWithTax();
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Order;
use App\Cart;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'surname', 'birthdate', 'phone', 'address', 'city', 'zipcode', 'country' 
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'admin'
    ];

    public function orders(){
        return $this->belongsToMany(App\Order::class);
    }

    public function getFullName(){
        return $this->name . ' ' . $this->surname;
    }

    public function isAdmin(){
        return (bool) $this->admin;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\StoreUser;
use App\User;
use Auth;


class UserController extends Controller
{
    public function index()
    {
        $user = Auth::user();
        return view('user.userprofile', compact('user'));
    }

  

    public function update(StoreUser $request)
    {
        $user = Auth::user();
        $user->update($request->all());
        return redirect()->route('profile')
        				->withStatus('Profile updated');
    }
}

resources/views/user/cart.blade.php
@extends('layouts.app')

@section('content')

@section ('title', 'Cart')

@include('partials.errors', ['errors'=>$errors])
<div class="row">
	<div class="col-md-6 col-md-offset-3 text-center">	
		<a class="btn btn-medium" href="{{route('dishes_list')}}">Return to menu</a>
	</div>
</div>

<div class="row text-center">
@foreach($dishes->chunk(3) as $chunk)
  <div class="row">
  @foreach($chunk as $dish)
    <div class="col-md-4">
      <div class="thumbnail">
        <img  class="img-thumbnail img-responsive" style = "width:304px; height:236px;" src="{{ $dish->getPhotoUrl() }}">
        <div class="caption">
          <h3>{{$dish->title}}</h3>
          <p>Price: {!!$dish->price!!}</p>
          <p>Quantity: {{$cart->get($dish->id)}}</p>
          <p>Sale price: {!!$dish->getSalePrice()!!}</p>
          <p>Total Price: {{$cart->get($dish->id)*$dish->price}}</p>
          <p>Total Sale Price: {{$cart->get($dish->id)*$dish->getSalePrice()}}</p>
          {!! Form::open(['route' => ['cart.destroy', $dish->id], 'method' => 'DELETE'])!!}
          <p>{!! Form::submit('Remove from cart', ['class'=>'btn btn-warning']) !!}</p>
  		    {!! Form::close() !!}
        </div>
      </div>
    </div>
   @endforeach
  </div>
@endforeach
</div>


<div class="row">
	<div class="col-md-6 col-md-offset-3">
  	<div class="thumbnail">
		<div class="caption">
      <h3>Payment information</h3>
      <p>Total Price: {{$total}}</p>
      <p>Total Sale price: {{$totalSalePrice}}</p>
    	{!! Form::open(['route' =>'orders.store','method' => 'GET'])!!}
	    <p>{!! Form::submit('Order', ['class'=>'btn btn-warning']) !!}</p>
	    {!! Form::close() !!}
   	</div>
	</div>
</div>


@endsection

resources/views/user/contact.blade.php
@extends('layouts.app')

@section('content')

@section ('title', 'Contacts')

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div>
                <div class="panel panel-primary">
                    <div class="text-center header">Contact Us</div>
                        <div class="panel-body text-center">
                            <p>Restaurant is always ready to delight you with perfectly prepared European dishes, attentive service, and pleasant environment.</p>
    						<p>Professional staff of the restaurant carefully creates a menu for every season and prepares every meal you order with the utmost care. The restaurant offers elaborate gourmet meals inspired by the culinary art innovations and made by our chefs.</p>
    						<p>The restaurant’s interior is designed for your comfort and cosiness. A spacious, light, and modern environment allows you to relax and leisurely enjoy quality food.</p>
    						<p>You are kindly welcome to the restaurant every day and on your special occasions. The restaurant can serve around 160 guests at a time. It is an ideal venue for a business lunch or dinner, as well as for private occasions such as wedding parties, anniversary parties, and major public holidays.</p>
                                                    
                        </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div>
                <div class="panel panel-primary">
                    <div class="text-center header">Our Office</div>
                        <div class="panel-body text-center">
                            <h4>Address</h4>
                            <div>
                            Svitrigailos 5<br />
                            Vilnius<br />
                            #(8 5) 12345<br />
                            ahoi@ahoy.lt<br />
                            </div>
                            <hr />
                            <div id="map" class="map">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
  function initMap() {
    var uluru = {lat: 54.679333, lng: 25.266333};
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 17,
      center: uluru
    });
    var marker = new google.maps.Marker({
      position: uluru,
      map: map
    });
  }
</script>
<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBYdE-0PSN8EQ-FIHU11O_l3NfVSc9qRaU&callback=initMap">
</script>

@endsection

resources/views/user/menu.blade.php
@extends('layouts.app')

@section ('content')

@section ('title', 'Menu')

@include('partials.errors', ['errors'=>$errors])

@if (session('message'))
    <div class="alert alert-success">
        {{ session('message') }}
    </div>
@endif   

<div class="row">
	<div class="col-md-6 col-md-offset-3 text-center">	
		<a class="btn btn-medium" href="{{route('cart.index')}}">Basket: {{$cartCount}} item(s)</a>
	</div>
</div>

<div class="row text-center">
@foreach($dishes->chunk(2) as $chunk)
	<div class="row">
	@foreach($chunk as $dish)
	  <div class="col-md-6">
	    <div class="thumbnail">
	    	<div max with="304">
	      <img  class="img-thumbnail img-responsive" style = "width:304px; height:236px;" src="{{ $dish->getPhotoUrl() }}">
	      </div>
	      <div class="caption">
	        <h3>{{$dish->title}}</h3>
	        <p>{!!$dish->description!!}</p>
	        <p>Price: {!!$dish->price!!}</p>
	        <p>Sale price: {!!$dish->getSalePrice()!!}</p>
	        {!! Form::open((['route' => ['cart.update', $dish->id], 'method' => 'PUT']))!!}
	        <p>Quantity: {!! Form::selectRange('quantity', 1, 5) !!}</p>
	        <p>{!! Form::submit('Add to cart', ['class'=>'btn btn-warning'])!!}</p>
			{!! Form::close() !!}
	      </div>
	    </div>
	  </div>
	@endforeach
	</div>
	@endforeach
</div>
			





@endsection

resources/views/user/orders.blade.php
@extends('layouts.app')

@section('content')

@section ('title', 'Orders')

<div class="row">
	<div class="col-md-6 col-md-offset-3 text-center">	
		<a class="btn btn-medium" href="{{route('dishes_list')}}">Return to menu</a>
	</div>
</div>

@if (session('message'))
    <div class="alert alert-success">
        {{ session('message') }}
    </div>
@endif   

<div class="row">
	<div class="col-md-12">
		<table class="table table-hover table2 orders-table">
			<thead>
				<tr>
					<th>User Name</th>
					<th>Date</th>
					<th>Total</th>
					<th>Total with tax</th>
					<th>Order ID</th>
					<th>Customer ID</th>
				</tr>				
			</thead>
			@foreach($orders as $order)
			<tr>
				<td class="table2">{{ $order->user->getFullName() }}</td>	
				<td class="table2">{{ $order->created_at }}</td>
				<td class="table2">{{ $order->total }}</td>	
				<td class="table2">{{ $order->total_with_tax }}
				<td class="table2">{{ $order->id }}</td>
				<td class="table2">{{ $order->user_id }}</td>
			</tr>
			@endforeach
			<tr>
				
			</tr>
		</table>
	</div>
</div>

<div class="row">
	<div class="col-md-6 thumbnail text-center">
		<div class="bg-success"> Total: {{$orders->sum('total')}} Eur</div>
	</div>
	<div class="col-md-6 thumbnail text-center">
		<div class="bg-success"> Total with tax: {{$orders->sum('total_with_tax')}}	Eur</div>
	</div>	
</div>


@endsection

resources/views/user/reservation.blade.php
@extends('layouts.app')

@include('partials.errors', ['errors'=>$errors])

@section('content')

@section ('title', 'Reservation')

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-warning">
                <div class="panel-heading text-center">Reserve a table</div>
                    <div class="panel-body">                 
        		{!! Form::open(['route'=>'reservation.store', 'method' => 'post', 'class' => 'form-horizontal']) !!}

                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif   
                
                    <div class="form-group">
                       
                        <label class="col-sm-4 control-label">Name</label>
                       		<div class="col-sm-6">                                 
    						{{ Form::text('name', $name, ['class'=>'form-control', 'required'=>'required', 'placeholder'=>'Name'])}} 
    						</div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-4 control-label">Number of persons</label>
                          	<div class="col-sm-6">                              
                          	{!! Form::selectRange('persons', 1, 10, 1, ['class'=>'form-control']) !!}
                          	</div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-4 control-label">Date</label>
                            <div class="col-sm-6">                           
                            {!! Form::text('date', null, ['required'=>'required', 'class'=>'form-control', 'placeholder'=>'yyyy-mm-dd'])!!}
                     		</div>
                    </div>

                    <div class="form-group"sm>
                        <label class="col-sm-4 control-label">Time</label>
                        	<div class="col-sm-6">  
                            {!! Form::time('time', null, ['required'=>'required', 'class'=>'form-control'])!!}
                      		</div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-4 control-label">Phone</label>
    					    <div class="col-sm-6">                             
                            {!! Form::text('phone', $phone, ['required'=>'required', 'class'=>'form-control'])!!}
                       		</div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-6 col-sm-offset-4">                            
                {!! Form::submit('Book', ['class'=>'form-control btn btn-warning']) !!}                           
                        </div>
                    </div>
                {!! Form::close() !!}           
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/user/userprofile.blade.php
@extends('layouts.app')

@section ('content')

@section ('title', 'Profile')

@if (session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
@endif

<div class="row m-5">
	<div class="col-md-12 text-center">	
		<a class="btn " href="{{route('dishes_list')}}">Return to menu</a>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<table class="table table-hover table2 profile">
			<thead>
				<tr>
					<th>Name</th>
					<th>Surname</th>
					<th>Email</th>
					<th>Birthdate</th>
					<th>Phone</th>
					<th>Address</th>
					<th>City</th>
					<th>Zipcode</th>
					<th>Country</th>
				</tr>
			</thead>
			<tr>
				{!! Form::model($user, ['route' => ['updateprofile', $user->id], 'method' => 'PUT', 'class' => 'form-horizontal']) !!}
				<td>{!! Form::text('name', null, ['class'=>'form-control', 'required'=>'required'])!!}</td>
				<td>{!! Form::text('surname', null, ['class'=>'form-control', 'required'=>'required']) !!} </td>
				<td>{!! Form::text('email', null, ['class'=>'form-control', 'required'=>'required']) !!} </td>
				<td>{!! Form::text('birthdate', null, ['class'=>'form-control', 'required'=>'required'])!!}</td>
				<td>{!! Form::text('phone', null, ['class'=>'form-control', 'required'=>'required'])!!}</td>
				<td>{!! Form::text('address', null, ['class'=>'form-control', 'required'=>'required'])!!}</td>
				<td>{!! Form::text('city', null, ['class'=>'form-control', 'required'=>'required'])!!}</td>
				<td>{!! Form::text('zipcode', null, ['class'=>'form-control', 'required'=>'required'])!!}</td>
				<td>{!! Form::text('country', null, ['class'=>'form-control', 'required'=>'required'])!!}</td>
				<td>{!! Form::submit('Save', ['class'=>'btn btn-warning']) !!}</td>	
				{!! Form::close() !!}
			</tr>
		</table>	
	</div>
</div>

@endsection