routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware'=>'auth'], function(){
	Route::get('/orders/user', 'OrdersController@userIndex')->name('orders.user');
	Route::get('/orders/store', 'OrdersController@store')->name('orders.store');
	Route::get('/userprofile', 'UserController@index')->name('profile');
	Route::put('/userprofile', 'UserController@update')->name('updateprofile');
});

Route::group(['middleware'=>['auth', 'admin']], function(){
	Route::resource('/admin/dishes', 'AdminDishController', ['as'=>'admin']);
	Route::resource('/orders', 'OrdersController', ['except'=>['store']]);
	Route::resource('/reservation', 'TableReservationController');
	Route::resource('/adminusers', 'AdminUserController');
});

Route::get('/reservation/create', 'TableReservationController@create')->name('reservation.create');
Route::post('/reservation', 'TableReservationController@store')->name('reservation.store');

Route::get('/home', 'HomeController@index');
Route::get('/dishes', 'DishController@index')->name('dishes_list');
Route::get('/contacts', function (){
	return view('user.contact');
})->name('contacts');
Route::resource('cart', 'CartController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Order;
use App\Cart;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'surname', 'birthdate', 'phone', 'address', 'city', 'zipcode', 'country' 
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'admin'
    ];

    public function orders(){
        return $this->belongsToMany(App\Order::class);
    }

    public function getFullName(){
        return $this->name . ' ' . $this->surname;
    }

    public function isAdmin(){
        return (bool) $this->admin;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\StoreUser;
use App\User;
use Auth;


class UserController extends Controller
{
    public function index()
    {
        $user = Auth::user();
        return view('user.userprofile', compact('user'));
    }

  

    public function update(StoreUser $request)
    {
        $user = Auth::user();
        $user->update($request->all());
        return redirect()->route('profile')
        				->withStatus('Profile updated');
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.app')

@section('content')

@section ('title', 'Create user')

@include('partials.errors', ['errors'=>$errors])



<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Register</div>
                    <div class="panel-body">
                
                    {!! Form::open(['route'=> 'adminusers.store', 'method'=>'post', 'class' => 'form-horizontal']) !!}
                    {{ csrf_field() }}

                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                        <label for="name" class="col-md-4 control-label">Name</label>

                        <div class="col-md-6">
                            <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                            @if ($errors->has('name'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('surname') ? ' has-error' : '' }}">
                        <label for="surname" class="col-md-4 control-label">Surname</label>

                        <div class="col-md-6">
                            <input id="surname" type="text" class="form-control" name="surname" value="{{ old('surname') }}" required autofocus>

                            @if ($errors->has('surname'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('surname') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('birthdate') ? ' has-error' : '' }}">
                        <label for="birthdate" class="col-md-4 control-label">Birth Date</label>

                        <div class="col-md-6">
                            <input id="birthdate" type="text" class="form-control" name="birthdate" value="{{ old('birthdate') }}" required autofocus>

                            @if ($errors->has('birthdate'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('birthdate') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
                        <label for="phone" class="col-md-4 control-label">Phone</label>

                        <div class="col-md-6">
                            <input id="phone" type="text" class="form-control" name="phone" value="{{ old('phone') }}" required autofocus>

                            @if ($errors->has('phone'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('phone') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                        <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                        <div class="col-md-6">
                            <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required>

                            @if ($errors->has('email'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('email') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
                        <label for="address" class="col-md-4 control-label">Address</label>

                        <div class="col-md-6">
                            <input id="city" type="text" class="form-control" name="address" value="{{ old('address') }}" required>

                            @if ($errors->has('address'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('address') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('city') ? ' has-error' : '' }}">
                        <label for="city" class="col-md-4 control-label">City</label>

                        <div class="col-md-6">
                            <input id="city" type="text" class="form-control" name="city" value="{{ old('city') }}" required>

                            @if ($errors->has('city'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('city') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('country') ? ' has-error' : '' }}">
                        <label for="country" class="col-md-4 control-label">Country</label>

                        <div class="col-md-6">
                            <input id="country" type="text" class="form-control" name="country" value="{{ old('country') }}" required>

                            @if ($errors->has('country'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('country') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('zipcode') ? ' has-error' : '' }}">
                        <label for="zipcode" class="col-md-4 control-label">Zipcode</label>

                        <div class="col-md-6">
                            <input id="zipcode" type="text" class="form-control" name="zipcode" value="{{ old('country') }}" required>

                            @if ($errors->has('zipcode'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('zipcode') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                        <label for="password" class="col-md-4 control-label">Password</label>

                        <div class="col-md-6">
                            <input id="password" type="password" class="form-control" name="password" required>

                            @if ($errors->has('password'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('password') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                        <div class="col-md-6">
                            <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-4">
                            {!! Form::submit('Create', ['class'=>'btn btn-success']) !!}
							{!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')

@section ('title', 'Edit user')

@include('partials.errors', ['errors'=>$errors])


{!! Form::model($user, ['route' => ['adminusers.update', $user->id], 'method' => 'PUT', 'class' => 'form-horizontal']) !!}

<table class="table table-hover table2 profile">
	<thead>
		<th>Name</th>
		<th>Surname</th>
		<th>Email</th>
		<th>Birthdate</th>
		<th>Phone</th>
		<th>Address</th>
		<th>City</th>
		<th>Zipcode</th>
		<th>Country</th>
		<th></th>
	</thead>
	
	<tr>
		<td>{!! Form::text('name', null, ['class'=>'form-control', 'required'=>'required'])!!}</td>
		<td>{!! Form::text('surname', null, ['class'=>'form-control', 'required'=>'required']) !!} </td>
		<td>{!! Form::text('email', null, ['class'=>'form-control', 'required'=>'required']) !!} </td>
		<td>{!! Form::text('birthdate', null, ['class'=>'form-control', 'required'=>'required'])!!}</td>
		<td>{!! Form::text('phone', null, ['class'=>'form-control', 'required'=>'required'])!!}</td>
		<td>{!! Form::text('address', null, ['class'=>'form-control', 'required'=>'required'])!!}</td>
		<td>{!! Form::text('city', null, ['class'=>'form-control', 'required'=>'required'])!!}</td>
		<td>{!! Form::text('zipcode', null, ['class'=>'form-control', 'required'=>'required'])!!}</td>
		<td>{!! Form::text('country', null, ['class'=>'form-control', 'required'=>'required'])!!}</td>
		<td>{!! Form::submit('Save', ['class'=>'btn btn-warning']) !!}</td>
	</tr>
</table>	

{!! Form::close() !!}


@endsection

resources/views/admin/users/list.blade.php
@extends('layouts.app')

@section('content')

@section ('title', 'List of users')

@include('partials.errors', ['errors'=>$errors])


<div class="row m-5">
	<div class="col-md-6 text-center">	
		<p>Welcome, {{ Auth::user()->name }}</p>
	</div>

	<div class="col-md-6 text-center">	
		<a class="btn btn-primary btn-medium" href="{{ route('adminusers.create') }}">Create new User</a>
	</div>
</div>

<div class="row m-5">
	<table class="table table-hover table2 profileadmin">
		<thead>
			<th>Name</th>
			<th>Surname</th>
			<th>User ID</th>
			<th>Email</th>
			<th>Birthdate</th>
			<th>Phone</th>
			<th>Address</th>
			<th>City</th>
			<th>Zipcode</th>
			<th>Country</th>
			<th></th>
		</thead>

	@foreach($users as $user)
		<tr>
			<td>{{$user->name}}</td>
			<td>{{$user->surname}}</td>
			<td>{{$user->id}}</td>
			<td>{!!$user->email!!}</td>		
			<td>{!!$user->birthdate!!}</td>
			<td>{!!$user->phone!!}</td>
			<td>{!!$user->address!!}</td>
			<td>{!!$user->city!!}</td>
			<td>{!!$user->zipcode!!}</td>
			<td>{!!$user->country!!}</td>
	@if($user->id != Auth::user()->id)
			<td> 
				<a class="btn btn-warning" href="{{route('adminusers.edit', [$user->id])}}">Edit </a>
			</td>
			<td>
				{!! Form::open(['route' => ['adminusers.destroy', $user->id], 'method' => 'DELETE'])!!}
				{!! Form::submit('Delete', ['class'=>'btn btn-warning']) !!}
				{!! Form::close() !!}
			<td>
	@else
			<td colspan="2"></td>
	@endif
		</tr>
	@endforeach
	</table>	
</div>

@endsection