routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware'=>'auth'], function(){
	Route::get('/orders/user', 'OrdersController@userIndex')->name('orders.user');
	Route::get('/orders/store', 'OrdersController@store')->name('orders.store');
	Route::get('/userprofile', 'UserController@index')->name('profile');
	Route::put('/userprofile', 'UserController@update')->name('updateprofile');
});

Route::group(['middleware'=>['auth', 'admin']], function(){
	Route::resource('/admin/dishes', 'AdminDishController', ['as'=>'admin']);
	Route::resource('/orders', 'OrdersController', ['except'=>['store']]);
	Route::resource('/reservation', 'TableReservationController');
	Route::resource('/adminusers', 'AdminUserController');
});

Route::get('/reservation/create', 'TableReservationController@create')->name('reservation.create');
Route::post('/reservation', 'TableReservationController@store')->name('reservation.store');

Route::get('/home', 'HomeController@index');
Route::get('/dishes', 'DishController@index')->name('dishes_list');
Route::get('/contacts', function (){
	return view('user.contact');
})->name('contacts');
Route::resource('cart', 'CartController');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title')</title>

    <!-- Styles -->
    <link href="/css/app.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
   
    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
  <script>tinymce.init({ selector:'textarea' });</script>
</head>
<body class="background">


    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="/">Restaurant Ahoi</a>
                    <a class="navbar-brand" href="/"><img class="img-responsive" width="50" height="50" src="{{$url = asset('/images/logo.png')}}" /></a>

                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->

                            <li><a href="{{ route('dishes_list') }}">Dishes menu</a></li>
                            <li><a href="{{ route('reservation.create') }}">Table reservation</a></li>
                            <li><a href="{{ route('cart.index') }}"> <i class="fa fa-shopping-cart" aria-hidden="true"></i> :{{$cartCount}}</a></li>
                            <li><a href="{{ route('contacts') }}">Contacts</a></li>

                            @if (Auth::guest())
                                <li><a href="{{ url('/login') }}">Login</a></li>
                                <li><a href="{{ url('/register') }}">Register</a></li>
                            @else
                                @if (Auth::check() && Auth::user()->isAdmin())
                                    <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                                Admin <span class="caret"></span>
                                            </a>
                                            <ul class="dropdown-menu" role="menu">
                                                <li><a href="{{ route('reservation.index') }}">Administrate reservations of tables</a></li>
                                                <li><a href="{{ route('admin.dishes.index') }}">Administrate dishes menu</a></li>
                                                <li><a href="{{ route('orders.index') }}">Administrate orders</a></li>
                                                <li><a href="{{ route('adminusers.index') }}">Administrate users</a></li>
                                            </ul>
                                    </li>
                                @endif
                                <li><a href="{{ route('orders.user') }}">Orders</a></li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                        {{ Auth::user()->name }} <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="{{ route('profile') }}">User profile</a></li>
                                        <li>
                                            <a href="{{ url('/logout') }}"
                                                onclick="event.preventDefault();
                                                         document.getElementById('logout-form').submit();">
                                                Logout
                                            </a>

                                            <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                                {{ csrf_field() }}
                                            </form>
                                        </li>
                                    </ul>
                                </li>
                        @endif

                    </ul>
                </div>
            </div>
        </nav>
    </div>
    
        <div class="container">
            @yield('error')  
            @yield('content')
        </div>
<footer class="footer">
    <div class="row">
        <div class="col-md-12 navbar navbar-default navbar-fixed-bottom text-center">
            <p> 3WA Academy | Final Project | <span><i class="fa fa-copyright" aria-hidden="true"></i></span> </p>
        </div>
    </div>
</footer>
    <!-- Scripts -->
    <script src="/js/app.js"></script>
</body>

</html>