routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware'=>'auth'], function(){
	Route::get('/orders/user', 'OrdersController@userIndex')->name('orders.user');
	Route::get('/orders/store', 'OrdersController@store')->name('orders.store');
	Route::get('/userprofile', 'UserController@index')->name('profile');
	Route::put('/userprofile', 'UserController@update')->name('updateprofile');
});

Route::group(['middleware'=>['auth', 'admin']], function(){
	Route::resource('/admin/dishes', 'AdminDishController', ['as'=>'admin']);
	Route::resource('/orders', 'OrdersController', ['except'=>['store']]);
	Route::resource('/reservation', 'TableReservationController');
	Route::resource('/adminusers', 'AdminUserController');
});

Route::get('/reservation/create', 'TableReservationController@create')->name('reservation.create');
Route::post('/reservation', 'TableReservationController@store')->name('reservation.store');

Route::get('/home', 'HomeController@index');
Route::get('/dishes', 'DishController@index')->name('dishes_list');
Route::get('/contacts', function (){
	return view('user.contact');
})->name('contacts');
Route::resource('cart', 'CartController');

app/Dish.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Dish extends Model
{
    protected $fillable = ['title', 'description', 'quantity', 'price', 'saleprice', 'photo'];

    public function getPhotoUrl(){
    	return asset('uploads/' . $this->photo);
    }

    public function getSalePrice(){
    	return $this->price * 1.21;
    }
}

app/Http/Controllers/DishController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Dish;
use App\Http\Controllers\CartController;
use App\Cart;



class DishController extends Controller
{
   

	public function index(Request $request){

	$cart = $request->session()->get('cart', new Cart());
	$cartCount = $cart->count();
   $dishes = Dish::all();
   return view('user.menu', compact('dishes', 'cartCount'));
	}
}

resources/views/admin/dishes/create.blade.php
@extends('layouts.app')


@section ('content')

@section ('title', 'Create dish')

@include('partials.errors', ['errors'=>$errors])

<div class="table-responsive">
	<table class="table table-hover table2">
		<thead>
			<th>Title</th>
			<th>Description</th>
			<th>Quantity</th>
			<th>Price</th>
			<th>Photo</th>
			<th></th>
		</thead>

		<tr class="createdish">
		{!! Form::open(['route'=> 'admin.dishes.store', 'files' => true, 'class' => 'form-horizontal']) !!}
			<td>{!! Form::text('title', null, ['class'=>'form-control', 'required'=>'required'])!!}</td>
			<td>{!! Form::textarea('description', null, ['class'=>'form-control']) !!} </td>
			<td>{!! Form::selectRange('quantity', 1, 10, 1, ['class'=>'form-control']) !!} </td>
			<td>{!! Form::text('price', null, ['class'=>'form-control', 'required'=>'required'])!!}</td>
			<td>{!! Form::file('photo', ['class'=>'form-control']) !!}</td>
			<td>{!! Form::submit('Create', ['class'=>'btn btn-success']) !!}</td>
			{!! Form::close() !!}
		</tr>
	</table>
</div>
@endsection

 

resources/views/admin/dishes/edit.blade.php
@extends('layouts.app')


@section ('content')

@section ('title', 'Edit dish')

@include('partials.errors', ['errors'=>$errors])

{!! Form::model($dish, ['route' => ['admin.dishes.update', $dish->id], 'method' => 'PUT', 'files'=> true, 'class' => 'form-horizontal']) !!}

<div class="form-group">                            
    <label class="col-sm-4 control-label">Title</label>
   		<div class="col-sm-6">                                 
		{!! Form::text('title', null, ['required'=>'required', 'class'=>'form-control'])!!} 
		</div>
</div>

<div class="form-group">                            
    <label class="col-sm-4 control-label">Description</label>
   		<div class="col-sm-6">                                 
		{!! Form::textarea('description') !!}
		</div>
</div>

<div class="form-group">                            
    <label class="col-sm-4 control-label">Quantity</label>
   		<div class="col-sm-6">                                 
		{!! Form::selectRange('quantity', 1, 5) !!}
		</div>
</div>

<div class="form-group">                            
    <label class="col-sm-4 control-label">Price</label>
   		<div class="col-sm-6">                                 
		{!! Form::text('price', null, ['required'=>'required', 'class'=>'form-control'])!!}
		</div>
</div>

<div class="form-group">                            
    <label class="col-sm-4 control-label">Sale Price</label>
   		<div class="col-sm-6">                                 
		{!!$dish->getSalePrice()!!}
		</div>
</div>

<div class="form-group">                            
    <label class="col-sm-4 control-label">Sale Price</label>
   		<div class="col-sm-6">                                 
		{!! Form::file('photo') !!}
		</div>
</div>

<div class="form-group">
    <div class="col-sm-6 col-sm-offset-4">   
		<img class="responsive img-thumbnail" style = "width:304px; height:236px;" src="{{ $dish->getPhotoUrl() }}">
    </div>
</div>

<div class="form-group">
    <div class="col-sm-6 col-sm-offset-4">      
	{!! Form::submit('Save', ['class'=>'btn btn-warning']) !!}
    </div>
</div>

{!! Form::close() !!}


@endsection

resources/views/admin/dishes/list.blade.php
@extends('layouts.app')

@include('partials.errors', ['errors'=>$errors])

@section ('content')

@section ('title', 'List of dishes')

<div class="row m-5">
	<div class="col-md-6 text-center">	
		<p>Welcome, {{ Auth::user()->name }}</p></p>
	</div>

	<div class="col-md-6 text-center">	
		<a class="btn btn-primary btn-medium" href="{{route('admin.dishes.create')}}">Create new dish</a>
	</div>
</div>

<div class="row m-5">
	<table class="table table-hover text-center table2">
		<thead>
			<th class="text-center">ID</th>
			<th class="text-center">Title</th>
			<th class="text-center">Description</th>
			<th class="text-center">Quantity</th>
			<th class="text-center">Price</th>
			<th class="text-center">Sale Price</th>
			<th class="text-center">Photo</th>
			<th></th>
			<th></th>
			<th></th>
		</thead>
				
		@foreach($dishes as $dish)
		<tr class="dishlist">
			<td>{{$dish->id}}</td>
			<td>{{$dish->title}}</td>
			<td>{!!$dish->description!!}</td>		
			<td>{!! Form::selectRange('quantity', 1, 5) !!} </td>
			<td>{!!$dish->price!!}</td>
			<td>{!!$dish->getSalePrice()!!}</td>
			<td>
				<img  class="img-thumbnail img-responsive" style = "width:304px; height:236px;" src="{{ $dish->getPhotoUrl() }}">
			</td>
			<td> 
				<a class="btn btn-warning" href="{{route('admin.dishes.edit', [$dish->id])}}">Edit </a>
			</td>
			<td>
				{!! Form::open(['route' => ['admin.dishes.destroy', $dish->id], 'method' => 'DELETE'])!!}
				{!! Form::submit('Delete', ['class'=>'btn btn-warning']) !!}
				{!! Form::close() !!}
			</td>
		</tr>
		@endforeach
	</table>
</div>
@endsection